name: 'Test'

on:
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ["aarch64", "amd64", "armhf", "armv7", "i386"]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Test build
      uses: home-assistant/builder@2023.08.0
      with:
        args: |
          --${{ matrix.arch }} \
          --target samba \
          --test
